[functions]
  external_node_modules = ["express", "cors"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/server/index/:splat"
[[redirects]]
  from = "/*"
  status = 200
  to = "/"